services:
    ofelia:
        image: mcuadros/ofelia:latest
        container_name: ofelia

        restart: unless-stopped

        command: daemon --docker

        labels:
            com.centurylinklabs.watchtower.enable: "true"

        environment:
            TZ: ${TZ}

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro

        network_mode: none
