services:
    traefik:
        image: "traefik:3"
        container_name: traefik

        restart: unless-stopped

        healthcheck:
            test:
                ["CMD", "wget", "--spider", "-q", "http://localhost:8080/ping"]

        labels:
            traefik.enable: "true"
            traefik.docker.network: "traefik_network"

            # Configure the web UI
            traefik.http.routers.traefik-ui.entrypoints: "web"
            traefik.http.routers.traefik-ui.rule: "Host(`traefik.home.janlucaklees.de`)"
            traefik.http.routers.traefik-ui.service: "api@internal"
            # HTTPS router (the one that actually serves the dashboard)
            traefik.http.routers.traefik-ui-secure.entrypoints: "websecure"
            traefik.http.routers.traefik-ui-secure.rule: "Host(`traefik.home.janlucaklees.de`)"
            traefik.http.routers.traefik-ui-secure.tls: true
            traefik.http.routers.traefik-ui-secure.service: "api@internal"

            com.centurylinklabs.watchtower.enable: "true"

        command:
            - "--api"
            - "--ping=true"
            - "--log.level=DEBUG"

            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--providers.docker.network=traefik_network"
            - "--providers.file.filename=/etc/traefik/config.yml"

            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"

            - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
            - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

        environment:
            TZ: "${TZ}"

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./config.yml:/etc/traefik/config.yml
            - letsencrypt:/etc/letsencrypt:ro

        networks:
            - traefik_network

        ports:
            - "80:80"
            - "443:443"

    certbot:
        image: certbot/certbot:latest
        container_name: certbot

        command:
            [
                "certonly",
                "--manual",
                "--preferred-challenges",
                "dns",
                "-d",
                "home.janlucaklees.de,*.home.janlucaklees.de",
                "-m",
                "email@janlucaklees.de",
                "--agree-tos",
                "--no-eff-email",
            ]

        volumes:
            - letsencrypt:/etc/letsencrypt

volumes:
    letsencrypt:
        driver: local

networks:
    traefik_network:
        name: traefik_network
