version: "3.8"

services:
    traefik:
        image: "traefik:2"

        healthcheck:
            test:
                ["CMD", "wget", "--spider", "-q", "http://localhost:8080/ping"]

        labels:
            traefik.enable: "true"
            traefik.docker.network: "traefik_network"

            # Configure the web UI
            traefik.http.routers.traefik-ui.entrypoints: "web"
            traefik.http.routers.traefik-ui.rule: "Host(`traefik.janlucaklees.local`)"
            traefik.http.routers.traefik-ui.service: "api@internal"
            # traefik.http.routers.traefik-ui.tls.certresolver: "letsencrypt"
            # traefik.http.routers.traefik-ui.middlewares: "traefik-ui-auth"
            traefik.http.services.traefik-ui.loadbalancer.server.port: "8080"
            # traefik.http.middlewares.traefik-ui-auth.basicauth.usersfile: "/run/secrets/traefik_ui_basicauth"

        command:
            - "--api"
            - "--ping=true"
            - "--log.level=DEBUG"

            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--providers.docker.network=traefik_network"

            - "--entrypoints.web.address=:80"
            # - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
            # - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
            # - "--entrypoints.websecure.address=:443"

            # - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
            # - "--certificatesresolvers.letsencrypt.acme.email=email@janlucaklees.de"
            # - "--certificatesresolvers.letsencrypt.acme.storage=/.letsencrypt/acme.json"

        environment:
            TZ: "${TZ}"

        # secrets:
        #     - traefik_ui_basicauth

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro

            # - letsencrypt:/.letsencrypt

        networks:
            - traefik_network

        ports:
            - "80:80"
            - "443:443"

# secrets:
#     traefik_ui_basicauth:
#         external: true

volumes:
    letsencrypt:
        driver: local

networks:
    traefik_network:
        name: traefik_network
