version: '3.3'


services:

  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:${HOME_ASSISTANT_TAG}
    privileged: true
    restart: unless-stopped

    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

    environment:
      TZ: ${TZ}

    volumes:
      - ${HOME_ASSISTANT_CONFIG_DIR}:/config:cached

    ports:
      - ${HOME_ASSISTANT_PORT}:8123
