porkbun_api_key: ENC[AES256_GCM,data:UFRQr/OSPBvitcawFQGIPqS6/J1/mUfucqKoLxgcRbuPvyUg00CMMrVLd2UsDCl6Wh7U2zBLma8f5y+JHE7hXtLsTbw=,iv:bLaLEeiVzG0kUCbcDEpNx7PDKiuoAiQMFPsSGoatEEA=,tag:c04GYcGB/9rzrDaPL+iTxg==,type:str]
porkbun_secret_api_key: ENC[AES256_GCM,data:MrSPYPRiuPPRtBW7zef39Ut7oFHmU/S6aZukoLdB2NsYoc8eiC10xc05sQTZ9MFtW+eekJoxQflbJPlx6xudXAtj9AU=,iv:yq9dZzktH+JOjsQVS1hoIgYQxhtV5jXu/OKk+JngPRM=,tag:zlwDuKBqiCJ14JxNFKk83g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNUl6MjI3NTNxb2EyR3ox
            SHg1UHBKM01PYTZVUlI2SHNEZHQ4eXVnMVc0CnkrakZZOWJTbFNiVWFONWhXVTc2
            bXpZRG5IZ21CQ3hZcnp6R2xmYTdGSjQKLS0tIGR4UUM3RkhqQ1VMZUpaL3FqMk9y
            aVMrbmhvcVVOZ1YvNmJwVVlxRENlY1kKwzcwLdhohiiPNabU4PDzkilknkJEC2Ks
            B1fcAyH53l08RD6RzUq8VPT5H0Zej4Xpk/d9prpsAmSHiTxgbi6Ddg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wwuwdvq20fq35aku93qgw9fj2uxeu7kxlgwg4zrrr9zx4s8vuuvsjn5t3g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcFlNa1d0cThQeDJqL2F2
            cjJSck1MTUZweGdqelFqSjZOdFZCTERqN3lBCmVWd0JEWWdLTnZOaWpQQnR2dWMv
            VzA5MnVzcDg0bHdFdFAyUkJjSGFZbmMKLS0tIEtMN2YyWE1uR2ZwMk1DazNIZ3Ns
            Q0VtZ2JWL3NMNjhEOUpOUUxSenVOVWMK2RaWCMbXu5khb+jOMyEzZinMiSpmjApI
            qbe5NX2jQuecd401kVF+YwTvUr+DLdVkCa9I/nvPUDB1BShGTQp4JQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age142s7lfpzjdddrrxkee8gr057u9hqkanu220n4f6hvzmr9n66x4rs9w3zvs
    lastmodified: "2026-10-02T17:41:27Z"
    mac: ENC[AES256_GCM,data:nmKHJx6fyLYpfEyavQlkhA6WubYIoZQ0YS1RkdIHOq6NQt7z7w41RxjYnZNdJ2RxulOG55kmxF1zrtLFtRIM0K02m8UZaXQyXozpEVlBJezwb0tl3+6RYc1wmhNPkPdU3iWdVfYBsZ5taj09bUXkJy/g9BZ/NI5F1TMul31uTJI=,iv:Z+0TCefyw/EcuIAbUzLrmO5QUf6Qlxyijdk7/M0wJe8=,tag:Oq8R9ee3NOAIc1ScR/wAOg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
