porkbun_api_key: ENC[AES256_GCM,data:UFRQr/OSPBvitcawFQGIPqS6/J1/mUfucqKoLxgcRbuPvyUg00CMMrVLd2UsDCl6Wh7U2zBLma8f5y+JHE7hXtLsTbw=,iv:bLaLEeiVzG0kUCbcDEpNx7PDKiuoAiQMFPsSGoatEEA=,tag:c04GYcGB/9rzrDaPL+iTxg==,type:str]
porkbun_secret_api_key: ENC[AES256_GCM,data:MrSPYPRiuPPRtBW7zef39Ut7oFHmU/S6aZukoLdB2NsYoc8eiC10xc05sQTZ9MFtW+eekJoxQflbJPlx6xudXAtj9AU=,iv:yq9dZzktH+JOjsQVS1hoIgYQxhtV5jXu/OKk+JngPRM=,tag:zlwDuKBqiCJ14JxNFKk83g==,type:str]
dashboard_htpasswd: ENC[AES256_GCM,data:6V7dxLbRqGFEmU145E/+XQ73GbQuJWIgIwjvjBzOPmZ/tjDUdbEfNXxuZJIL8UtLcKVNxjfpgkhi0V5ImQk8lg==,iv:XWxooN8J45jHGvOf6eM4m2j+FHYZj49bwHJgcjxp9MA=,tag:q1O+2s+8fTAp1sk/ym0yWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdUJ4aHZrVEZaRFZFMjl3
            RDFMUGtBNjIzMi9mditNVnl3b3hvSGl1TFFRCnJudkZpdHFaRmE3SkRBMTFLYmxv
            WFd0ZUxlN0d2SnR3L09sNkdBUDdPckEKLS0tIEVCYUY1TGdkYmZEUy9LcFFYenlW
            V05rZG9PaUh1ZFJvcTZVSUJycUVndEEKDVANyL0Jfs1JzgGzsBZr8Sn0wQaB9nDe
            aM5R1HenotiPeVIraeGdkGDnl/9IAiHJqq3GtnoANDQAPCykp69MgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16eygwufge3085w0xqqw2pmj0w7h93465s6u0e3sg7ueaxlpxhcnqyfmgd5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbFZhck52UzBUS1dja0RB
            UUZUUHQvWjJiVlpvRVFFVmplNEcxL1U5UmtNCjBheEJZcWQ5SFVvZTdtR0hLdHB4
            QUIra1NYMWNFUHhXeno5TnVuRUNTcTAKLS0tIGppaVhBNG9jcDZnWksxQWE2YzJD
            aHZma282eHZYNFk1ZkwxcXdzWDIzWVUKVl+UyffdskYZ9lQ0PPx4M8N/mjPA+Cfq
            1ncdxQV4AO4l8ieH5VoDiUROrjsUaCZ2aQVCCcDfIGvLYimVz/IxjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age142s7lfpzjdddrrxkee8gr057u9hqkanu220n4f6hvzmr9n66x4rs9w3zvs
    lastmodified: "2026-10-06T19:05:53Z"
    mac: ENC[AES256_GCM,data:h4O7oovnltjcz8Y/qAodGhieJJC3OfB8QgJ9Ss+pO4TnnvNmTeX3/azNGTYP9TmnnNGE0QtK4YfFyUE5bbW9HOTM3timDK8W/RNqK/m1/DiIvLCpJjkVfgX30Elpi6nAp9rMzlf9osTrHzG8ccQ/VorhqFlKpZGdQA7YCoI21nY=,iv:+s4byJzy3diphUsjawrfrH1lRMZsMdqQ9eP2y7PodAA=,tag:YEzI5vr5EUZ5S801d3Daxg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
