porkbun_api_key: ENC[AES256_GCM,data:YLlGvGoLER8=,iv:lCRUTZVTXrBCbhBaSzhqeN+WvEAO21o4yMMWvvsfqs0=,tag:uwYj3AfDH32SqZDD5+sa0Q==,type:str]
porkbun_secret_api_key: ENC[AES256_GCM,data:AU5P1r+GTNY=,iv:qICSrn4o462m4CmZinHKgr3GQtvLZHJ3zZgTXi0wims=,tag:60vp/Ro186rTEG4/Dw2L3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVlExZ2xUTTczZEZ6RFF4
            anN3aWdDQm8zS1ZQSkRHS0lDTTg0ZHc1RTBJCnN5cXB3SEttejEzbEo2RlhSQURL
            NzQxTkpwbFNxSWk2L3AzY3dXcUhYcTAKLS0tIGFJZm4wWW5veDZZcm9PRFlkTFBj
            Yy9PL2hFQzNTQWVSOEdGSEtqbG5maGMKj5jX0i1dKz3ktz1YoU+M7hyFXSQvAm1G
            uvs4/sT5oB1YKC25mjcU3cHM7Gb3m0ANao5OcnifeT/jcoytOFWq4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wwuwdvq20fq35aku93qgw9fj2uxeu7kxlgwg4zrrr9zx4s8vuuvsjn5t3g
    lastmodified: "2026-09-21T18:46:28Z"
    mac: ENC[AES256_GCM,data:2Imv2UZpg83cv2H6hzW685h2Cjy70DxS4LVI+LEatWnfO0287EPFbKzJk/xbDH9zF7bR51nA4Dxq5+r46fjIPRj2MS4xXgu7n1IpJ8fnHk4lwSIFhTfQnOQAHlbwvQLO1tS93j47UEvwpncaC9lsc8bp3KvnM+4EinpoOn9o6Rg=,iv:wBKKGquhyfa9w+OVRNEZLISH37mRLGiDTlbQV8HnPUc=,tag:9A6vT00FLrWD4xDe8LwXWw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
