name: kopia
port: 51515
domain: kopia
volumes:
  config: { class: pool }
  cache: { class: fast }
  logs: { class: fast }
  repo: { class: fast }
config:
  server_username: jlk
  repository: s3
  s3_endpoint: s3.eu-central-003.backblazeb2.com
  s3_bucket: storagebaby-kopia
secrets: [server_password, repository_password, b2_key_id, b2_application_key]
backup: none
