services:
    jellyfin:
        image: linuxserver/jellyfin:latest
        container_name: jellyfin

        restart: unless-stopped

        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8096/health"]

        labels:
            traefik.enable: "true"
            traefik.docker.network: "traefik_network"
            traefik.http.routers.jellyfin.entrypoints: "web"
            traefik.http.routers.jellyfin.rule: "Host(`jellyfin.klees`)"
            traefik.http.services.jellyfin.loadbalancer.server.port: "8096"

        environment:
            TZ: ${TZ}

            PUID: 1000
            PGID: 998

            JELLYFIN_PublishedServerUrl: jellyfin.klees

        volumes:
            - /pool/apps/jellyfin/volumes/jellyfin_config:/config
            - /pool/shared/media:/media:cached

        devices:
            - /dev/dri:/dev/dri

        networks:
            - traefik_network

networks:
    traefik_network:
        external: true
