version: '3.3'


services:

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:${TAG}
    restart: unless-stopped

    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      JELLYFIN_PublishedServerUrl: ${DOMAIN}

    volumes:
      - ${CONFIG_DIR}:/config:cached
      - ${MEDIA_ROOT}:/media:cached

    ports:
      - ${PORT}:8096

    devices:
      # Mount this for hardware accelleration.
      - /dev/dri:/dev/dri
